name: Update README.md

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Update year and age
        run: |
          year_now=$(date +%y)
          date_now=$(date +%s)
          date_birth=$(date -d "2007-07-20" +%s)
          age=$((($date_now - $date_birth) / 31536000))
          sed -E -i 's/Uptime: ([0-9]+) years/'"Uptime: $age years/" README.md
          sed -E -i 's/OS: Zikabyte-OS v2.0.([0-9]+)/'"OS: Zikabyte-OS v2.0.$year_now/" README.md
          
      - name: Commit and push changes
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update uptime and OS version" || echo "No changes to commit"
            git push
